#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/vecto
#    username: root
#    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true

spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 5000
