#default 공통설정
jwt-secret-key: "exampleSecretKey"

--- # local1 설정(기본 설정, 백종현)
spring:
  config:
    activate:
      on-profile: db-local1


--- # local2 설정(손찬혁)
spring:
  config:
    activate:
      on-profile: db-local2

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: